# [START gae_python37_cloudsql_config]
runtime: python37

env_variables:
  CLOUD_SQL_USERNAME: root
  CLOUD_SQL_PASSWORD: ClothONFly666
  CLOUD_SQL_DATABASE_NAME: ClothONFlyDB
  CLOUD_SQL_CONNECTION_NAME: cloth-on-fly:us-central1:clothonflydb
# [END gae_python37_cloudsql_config]